controller_manager:
  ros__parameters:
    update_rate: 1000

    gg_hexleg_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # gripper_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

gg_hexleg_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint11
      - joint21
      - joint31
      - joint41
      - joint12
      - joint22
      - joint32
      - joint42
      - joint1r
      - joint2r
      - joint3r
      - joint4r
      - joint1r1
      - joint2r1
      - joint3r1
      - joint4r1
      - joint1r2
      - joint2r2
      - joint3r2
      - joint4r2


    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true